API:
  BASE_URL: "https://api.nytimes.com/svc/"
  TIME_WIRES_CONTEXT: "news/v3/content/all/%s.json?limit=500&api-key="
  TIME_WIRES_CONTEXT_ALL: "news/v3/content/all/all.json?limit=500&api-key="
  TIME_WIRES_SECTIONS_LIST: "news/v3/content/section-list.json?api-key="
  BOOKS_CONTEXT: "books/v3/lists/full-overview.json?api-key="
  MOVIES_REVIEWS_CONTEXT: "movies/v2/reviews/search.json?query=godfather&api-key="
  ARTICLES_CONTEXT: "search/v2/articlesearch.json?q=election&api-key="
SCRAPING:
  CROME_USER_AGENT: "{'User-Agent': 'Chrome/39.0.2171.95'}"  
  MOZILLA_USER_AGENT: "{'User-Agent': 'Mozilla/5.0'}"
ELASTIC_SEARCH:
  API_URL: "http://34.255.105.149:9200"
  INDEX: "test-index"
